# Generated by Django 5.0.1 on 2024-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_partnerimport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerimport',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
