# Generated by Django 5.0.1 on 2024-02-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_partnerimport_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerImport',
        ),
    ]
