# Generated by Django 5.0.1 on 2024-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_delete_partnerimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yaml_file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Импорт товаров',
                'verbose_name_plural': 'Импорт товаров',
            },
        ),
    ]
