# Generated by Django 5.0.1 on 2024-02-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_import_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import_file',
            name='name',
        ),
    ]
